# em_3905_joint_ctrlr_params.yaml
#
# This file defines ackermann_controller parameter values used for simulating the bad car (brobot)

# Publish the joint states to joint_states.
joint_state_ctrlr:
  type: joint_state_controller/JointStateController
  publish_rate: 60

# Define Controlling Elements
# Orignal Parameters

# left_front_steering_ctrlr:
#   joint: left_front_steering_joint
#   type: effort_controllers/JointPositionController
#   pid: {p: 4.0, i: 0.0, d: 1.0}
# right_front_steering_ctrlr:
#   joint: right_front_steering_joint
#   type: effort_controllers/JointPositionController
#   pid: {p: 4.0, i: 0.0, d: 1.0}

# left_front_axle_ctrlr:
#   joint: left_front_axle
#   type: effort_controllers/JointVelocityController
#   pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}
# right_front_axle_ctrlr:
#   joint: right_front_axle
#   type: effort_controllers/JointVelocityController
#   pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}
# left_rear_axle_ctrlr:
#   joint: left_rear_axle
#   type: effort_controllers/JointVelocityController
#   pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}
# right_rear_axle_ctrlr:
#   joint: right_rear_axle
#   type: effort_controllers/JointVelocityController
#   pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}


left_front_steering_ctrlr:
  joint: left_front_steering_joint
  type: effort_controllers/JointPositionController
  pid: {p: 2.0, i: 0.0, d: 0.5}
right_front_steering_ctrlr:
  joint: right_front_steering_joint
  type: effort_controllers/JointPositionController
  pid: {p: 2.0, i: 0.0, d: 0.5}

# The D Part slows the System down, makes it ignore commands pretty much
left_front_axle_ctrlr:
  joint: left_front_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1.0, i: 0.1, d: 0.0, i_clamp: 0.0}
right_front_axle_ctrlr:
  joint: right_front_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1.0, i: 0.1, d: 0.0, i_clamp: 0.0}
left_rear_axle_ctrlr:
  joint: left_rear_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1.0, i: 0.1, d: 0.0, i_clamp: 0.0}
right_rear_axle_ctrlr:
  joint: right_rear_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1.0, i: 0.1, d: 0.0, i_clamp: 0.0}

