# brobot_ackermann_ctrlr_params.yaml
#
# This file defines ackermann_controller parameter values used for simulating the bad car (brobot)

left_front_wheel:
  steering_link_name: left_front_wheel
  steering_controller_name: left_front_steering_ctrlr
  axle_controller_name: left_front_axle_ctrlr
  diameter: 0.066

right_front_wheel:
  steering_link_name: right_front_wheel
  steering_controller_name: right_front_steering_ctrlr
  axle_controller_name: right_front_axle_ctrlr
  diameter: 0.066

left_rear_wheel:
  link_name: left_rear_wheel
  axle_controller_name: left_rear_axle_ctrlr
  diameter: 0.066

right_rear_wheel:
  link_name: right_rear_wheel
  axle_controller_name: right_rear_axle_ctrlr
  diameter: 0.066
